### ISSUE TITLE
3.9.0 not found in maven repo

### ISSUE THREAD

**Issue by codingtony** [mulesoft/mule-common#63]
Hi, 

I have a project with a dependency on 
G:org.mule.transports 
A:mule-transport-http
V:3.9.0

And it looks for mule-common 3.9.0 but it is not deployed to maven central nor on mule repo.

Can you release the version on a  maven repo ?

Thanks!

**Comment by aiannucci** [comment]
Hi @codingtony,
Thank you for reporting this. The artifact has been uploaded to the public MuleSoft repository. You should be able to find it now.
It will be uploaded to Maven Central soon.
